/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS;
    
    import javax.swing.*;
    import java.awt.*;
/**
 *
 * @author calvi
 */
public class MainMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MainMenuFrame() {
        initComponents();
        
         jScrollPane1.setViewportView(jPanelList);

    jPanelList.setLayout(new BoxLayout(jPanelList, BoxLayout.Y_AXIS));
    jPanelList.setAlignmentY(0.0f); // nempel atas
    jPanelList.setOpaque(true);
    jPanelList.setBackground(new Color(230, 230, 230));

    refreshList();
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEmail1 = new javax.swing.JLabel();
        jPanelRoot = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lbJudul = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        btnShowPass = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lbLoginvia = new javax.swing.JLabel();
        cbLoginVia = new javax.swing.JComboBox<>();
        lbCatatan = new javax.swing.JLabel();
        spCatatan = new javax.swing.JScrollPane();
        txtCatatan = new javax.swing.JTextArea();
        lbStatus = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        lbHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanelRight = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        cbSort = new javax.swing.JComboBox<>();
        cbFilter = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelList = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSetting = new javax.swing.JMenu();
        miChangeAkun = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        miLogout = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        lbEmail1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lbEmail1.setForeground(new java.awt.Color(255, 255, 255));
        lbEmail1.setText("Email");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelRoot.setBackground(new java.awt.Color(44, 62, 80));

        jPanelLeft.setBackground(new java.awt.Color(52, 73, 94));
        jPanelLeft.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.lightGray));

        lblTitle.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Game Account Manager");

        lbJudul.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        lbJudul.setForeground(new java.awt.Color(255, 255, 255));
        lbJudul.setText("Judul Akun");

        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbEmail.setText("Email");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/paimon no bg.png"))); // NOI18N

        Password.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");

        btnShowPass.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnShowPass.setText("Tampilkan");

        lbLoginvia.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        lbLoginvia.setForeground(new java.awt.Color(255, 255, 255));
        lbLoginvia.setText("Login via");

        cbLoginVia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbLoginVia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoyoverse", "Google", "Facebook" }));
        cbLoginVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoginViaActionPerformed(evt);
            }
        });

        lbCatatan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        lbCatatan.setForeground(new java.awt.Color(255, 255, 255));
        lbCatatan.setText("Catatan");

        txtCatatan.setColumns(20);
        txtCatatan.setRows(5);
        spCatatan.setViewportView(txtCatatan);

        lbStatus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbStatus.setText("Status Akun");

        cbStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Terjual", "Sold Out" }));

        lbHarga.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        lbHarga.setForeground(new java.awt.Color(255, 255, 255));
        lbHarga.setText("Harga (Rp)");

        btnSimpan.setBackground(new java.awt.Color(0, 204, 51));
        btnSimpan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnSimpan.setText("Simpan Akun");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBaru.setBackground(new java.awt.Color(204, 204, 204));
        btnBaru.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnBaru.setText("Baru");

        btnBack.setBackground(new java.awt.Color(220, 53, 69));
        btnBack.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(135, 135, 135))
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblTitle))
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelLeftLayout.createSequentialGroup()
                                .addComponent(btnBaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spCatatan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCatatan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJudul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJudul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLeftLayout.createSequentialGroup()
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowPass, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addComponent(cbStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLeftLayout.createSequentialGroup()
                                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLoginvia)
                                    .addComponent(cbLoginVia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHarga)
                                    .addComponent(txtHarga))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addComponent(lbJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowPass))
                .addGap(18, 18, 18)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoginvia)
                    .addComponent(lbHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoginVia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCatatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnBaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        jPanelRight.setBackground(new java.awt.Color(52, 73, 94));
        jPanelRight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.lightGray));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        cbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terbaru", "Terlama", "Harga" }));
        cbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSortActionPerformed(evt);
            }
        });

        cbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Belum Terjual", "Sold Out" }));
        cbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterActionPerformed(evt);
            }
        });

        jPanelList.setLayout(new javax.swing.BoxLayout(jPanelList, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(jPanelList);

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelRightLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSort, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSort, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelRootLayout = new javax.swing.GroupLayout(jPanelRoot);
        jPanelRoot.setLayout(jPanelRootLayout);
        jPanelRootLayout.setHorizontalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRootLayout.setVerticalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuSetting.setText("Setting");

        miChangeAkun.setText("Change Account");
        miChangeAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miChangeAkunActionPerformed(evt);
            }
        });
        menuSetting.add(miChangeAkun);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuSetting.add(miExit);

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        menuSetting.add(miLogout);

        jMenuBar1.add(menuSetting);

        menuHelp.setText("Help");

        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        menuHelp.add(miAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSortActionPerformed
        // TODO add your handling code here:
        refreshList();
    }//GEN-LAST:event_cbSortActionPerformed

    private void cbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterActionPerformed
        // TODO add your handling code here:
        refreshList();
    }//GEN-LAST:event_cbFilterActionPerformed

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void cbLoginViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoginViaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoginViaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
            String judul = txtJudul.getText().trim();
    String email = txtEmail.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();
    String loginVia = cbLoginVia.getSelectedItem().toString();
    String catatan = txtCatatan.getText().trim();
    String status = cbStatus.getSelectedItem().toString();

    int harga;
    try {
        harga = Integer.parseInt(txtHarga.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harga harus angka!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (judul.isEmpty() || loginVia.isEmpty() || txtHarga.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Judul dan Harga wajib diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    AkunGame akun = new AkunGame(judul, email, password, loginVia, catatan, status, harga);
    SystemManager.stok.add(akun);

    refreshList();
    clearForm();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         new LoginFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        refreshList();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        refreshList();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
    int ok = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin keluar aplikasi?",
        "Exit",
        JOptionPane.YES_NO_OPTION
    );

    if (ok == JOptionPane.YES_OPTION) {
        System.exit(0);
    }

    }//GEN-LAST:event_miExitActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
    int ok = JOptionPane.showConfirmDialog(
        this,
        "Logout dan kembali ke Login?",
        "Logout",
        JOptionPane.YES_NO_OPTION
    );
    if (ok == JOptionPane.YES_OPTION) {
        new LoginFrame().setVisible(true);
        this.dispose();
    }


    }//GEN-LAST:event_miLogoutActionPerformed

    private void miChangeAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miChangeAkunActionPerformed
        // TODO add your handling code here:
    int ok = JOptionPane.showConfirmDialog(
        this,
        "Ganti akun? Anda akan kembali ke halaman Login.",
        "Change Akun",
        JOptionPane.YES_NO_OPTION
    );

    if (ok == JOptionPane.YES_OPTION) {
        new LoginFrame().setVisible(true);
        this.dispose();
    }

    }//GEN-LAST:event_miChangeAkunActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
            this,
            "Game Account Manager\n" +
            "Versi 1.0\n\n" +
            "Aplikasi Java Swing (NetBeans)\n" +
            "Untuk mengelola akun game",
            "About",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_miAboutActionPerformed

private void refreshList() {
    jPanelList.removeAll();

    for (AkunGame akun : getFilteredList()) {
        jPanelList.add(createCardPanel(akun));
        jPanelList.add(Box.createVerticalStrut(12)); // jarak antar card
    }
    jPanelList.add(Box.createVerticalGlue());

    jPanelList.revalidate();
    jPanelList.repaint();
}
private JPanel createCardPanel(AkunGame akun) {
    JPanel card = new JPanel();
    card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
    card.setBackground(new Color(45, 52, 64));
    card.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(120, 120, 120)),
            BorderFactory.createEmptyBorder(12, 12, 12, 12)
    ));
    card.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblJudul = new JLabel(akun.getJudul());
    lblJudul.setForeground(Color.WHITE);
    lblJudul.setFont(lblJudul.getFont().deriveFont(Font.BOLD, 16f));
    lblJudul.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblInfo = new JLabel("Login via: " + akun.getLoginVia() + "   |   Status: " + akun.getStatus());
    lblInfo.setForeground(new Color(220, 220, 220));
    lblInfo.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblHarga = new JLabel("Harga: Rp " + akun.getHarga());
    lblHarga.setForeground(Color.WHITE);
    lblHarga.setFont(lblHarga.getFont().deriveFont(Font.BOLD, 14f));
    lblHarga.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblCatatan = new JLabel("<html><span style='color:#DDDDDD'>Catatan:</span> "
            + escapeHtml(akun.getCatatan()) + "</html>");
    lblCatatan.setForeground(new Color(220, 220, 220));
    lblCatatan.setAlignmentX(Component.LEFT_ALIGNMENT);

    JButton btnBeli = new JButton("Beli");
    btnBeli.setAlignmentX(Component.LEFT_ALIGNMENT);
    
    
    if ("Sold Out".equalsIgnoreCase(akun.getStatus())) {
        btnBeli.setEnabled(false);
        btnBeli.setText("Sold Out");
    }

    card.add(lblJudul);
    card.add(Box.createVerticalStrut(6));
    card.add(lblInfo);
    card.add(Box.createVerticalStrut(6));
    card.add(lblHarga);
    card.add(Box.createVerticalStrut(6));
    card.add(lblCatatan);
    card.add(Box.createVerticalStrut(10));
    card.add(btnBeli);

    return card;
}
private String escapeHtml(String s) {
    if (s == null) return "";
    return s.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;");
}


private void clearForm() {
    txtJudul.setText("");
    txtEmail.setText("");
    txtPassword.setText("");
    txtCatatan.setText("");
    txtHarga.setText("");

    cbLoginVia.setSelectedIndex(0);
    cbStatus.setSelectedIndex(0);
}
private java.util.List<AkunGame> getFilteredList() {
    String q = txtSearch.getText().trim().toLowerCase();
    String filter = cbFilter.getSelectedItem().toString();
    String sort = cbSort.getSelectedItem().toString();

    java.util.List<AkunGame> result = new java.util.ArrayList<>();

    // FILTER + SEARCH
    for (AkunGame akun : SystemManager.stok) {

        // filter status
        if (!"Semua".equalsIgnoreCase(filter)) {
            if (!akun.getStatus().equalsIgnoreCase(filter)) continue;
        }

        // search judul
        if (!q.isEmpty()) {
            String judul = akun.getJudul().toLowerCase();
            if (!judul.contains(q)) continue;
        }

        result.add(akun);
    }

    // ===== SORT =====
    if ("Terbaru".equalsIgnoreCase(sort)) {
        // biarin urutan default (yang terakhir ditambah di bawah)
        // supaya terbaru di atas → dibalik
        java.util.Collections.reverse(result);

    } else if ("Terlama".equalsIgnoreCase(sort)) {
        // urutan normal (tidak usah diapa-apain)

    } else if ("Harga".equalsIgnoreCase(sort)) {
        result.sort((a, b) -> Integer.compare(a.getHarga(), b.getHarga()));
    }

    return result;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnShowPass;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbFilter;
    private javax.swing.JComboBox<String> cbLoginVia;
    private javax.swing.JComboBox<String> cbSort;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelRoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCatatan;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmail1;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbLoginvia;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuSetting;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miChangeAkun;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JScrollPane spCatatan;
    private javax.swing.JTextArea txtCatatan;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
