/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS;
    
    import javax.swing.*;
    import java.awt.*;
    import UTS.PaymentFrame;

/**
 *
 * @author calvi
 */
public class MainMenuTamu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MainMenuTamu() {
        initComponents();
        
         jScrollPane1.setViewportView(jPanelList);

    jPanelList.setLayout(new BoxLayout(jPanelList, BoxLayout.Y_AXIS));
    jPanelList.setAlignmentY(0.0f); // nempel atas
    jPanelList.setOpaque(true);
    jPanelList.setBackground(new Color(230, 230, 230));

    refreshList();
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEmail1 = new javax.swing.JLabel();
        jPanelRoot = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanelRight = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        cbSort = new javax.swing.JComboBox<>();
        cbFilter = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelList = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        lbEmail1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lbEmail1.setForeground(new java.awt.Color(255, 255, 255));
        lbEmail1.setText("Email");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelRoot.setBackground(new java.awt.Color(44, 62, 80));
        jPanelRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLeft.setBackground(new java.awt.Color(52, 73, 94));
        jPanelLeft.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.lightGray));

        lblTitle.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Game Account Manager");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/paimon no bg.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UTS/yelan art no bg.png"))); // NOI18N

        btnBack.setBackground(new java.awt.Color(220, 53, 69));
        btnBack.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(135, 135, 135))
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelRoot.add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 800));

        jPanelRight.setBackground(new java.awt.Color(52, 73, 94));
        jPanelRight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.lightGray));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terbaru", "Terlama", "Harga" }));
        cbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSortActionPerformed(evt);
            }
        });

        cbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Belum Terjual", "Sold Out" }));
        cbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterActionPerformed(evt);
            }
        });

        jPanelList.setLayout(new javax.swing.BoxLayout(jPanelList, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(jPanelList);

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelRightLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSort, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSort, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelRoot.add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 13, 500, 800));

        jMenu1.setText("Setting");

        jMenuItem1.setText("Change Account");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        jMenu2.add(miAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSortActionPerformed
        // TODO add your handling code here:
        refreshList();
    }//GEN-LAST:event_cbSortActionPerformed

    private void cbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterActionPerformed
        // TODO add your handling code here:
        refreshList();
    }//GEN-LAST:event_cbFilterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        refreshList();
        new LoginFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
            this,
            "Game Account Manager\n" +
            "Versi 1.0\n\n" +
            "Aplikasi Java Swing (NetBeans)\n" +
            "Untuk mengelola akun game",
            "About",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_miAboutActionPerformed

private void refreshList() {
    jPanelList.removeAll();

    for (AkunGame akun : getFilteredList()) {
        jPanelList.add(createCardPanel(akun));
        jPanelList.add(Box.createVerticalStrut(12));
    }
    jPanelList.add(Box.createVerticalGlue());

    jPanelList.revalidate();
    jPanelList.repaint();
}
    public void refreshAfterPayment() {
    refreshList();
}
private JPanel createCardPanel(AkunGame akun) {
    JPanel card = new JPanel();
    card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
    card.setBackground(new Color(45, 52, 64));
    card.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(120, 120, 120)),
            BorderFactory.createEmptyBorder(12, 12, 12, 12)
    ));
    card.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblJudul = new JLabel(akun.getJudul());
    lblJudul.setForeground(Color.WHITE);
    lblJudul.setFont(lblJudul.getFont().deriveFont(Font.BOLD, 16f));
    lblJudul.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblInfo = new JLabel("Login via: " + akun.getLoginVia() + "   |   Status: " + akun.getStatus());
    lblInfo.setForeground(new Color(220, 220, 220));
    lblInfo.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblHarga = new JLabel("Harga: Rp " + akun.getHarga());
    lblHarga.setForeground(Color.WHITE);
    lblHarga.setFont(lblHarga.getFont().deriveFont(Font.BOLD, 14f));
    lblHarga.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblCatatan = new JLabel("<html><span style='color:#DDDDDD'>Catatan:</span> "
            + escapeHtml(akun.getCatatan()) + "</html>");
    lblCatatan.setForeground(new Color(220, 220, 220));
    lblCatatan.setAlignmentX(Component.LEFT_ALIGNMENT);

    JButton btnBeli = new JButton("Beli");
    btnBeli.setAlignmentX(Component.LEFT_ALIGNMENT);
    btnBeli.addActionListener(e -> {
    PaymentFrame pf = new PaymentFrame(this, akun);
    pf.setVisible(true);
});

    
    if ("Sold Out".equalsIgnoreCase(akun.getStatus())) {
        btnBeli.setEnabled(false);
        btnBeli.setText("Sold Out");
    }

    card.add(lblJudul);
    card.add(Box.createVerticalStrut(6));
    card.add(lblInfo);
    card.add(Box.createVerticalStrut(6));
    card.add(lblHarga);
    card.add(Box.createVerticalStrut(6));
    card.add(lblCatatan);
    card.add(Box.createVerticalStrut(10));
    card.add(btnBeli);
    
if (akun.isBuyerUnlocked()) {
    JLabel lblEmail = new JLabel("Email: " + akun.getEmail());
    lblEmail.setForeground(new Color(220, 220, 220));
    lblEmail.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel lblPass = new JLabel("Password: " + akun.getPassword());
    lblPass.setForeground(new Color(220, 220, 220));
    lblPass.setAlignmentX(Component.LEFT_ALIGNMENT);

    card.add(Box.createVerticalStrut(8));
    card.add(lblEmail);
    card.add(lblPass);
}

    return card;
}
private String escapeHtml(String s) {
    if (s == null) return "";
    return s.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;");
}


private void clearForm() {
    //txtJudul.setText("");
    //txtEmail.setText("");
    //txtPassword.setText("");
    //txtCatatan.setText("");
    //txtHarga.setText("");

   //cbLoginVia.setSelectedIndex(0);
    //cbStatus.setSelectedIndex(0);
}
/*private void handleBuy(AkunGame akun) {
    String[] metode = {"Dana", "Gopay", "OVO", "QRIS", "Bank BRI", "Bank Jago"};

    String pilih = (String) JOptionPane.showInputDialog(
            this,
            "Pilih metode pembayaran:",
            "Payment",
            JOptionPane.QUESTION_MESSAGE,
            null,
            metode,
            metode[0]
    );

    if (pilih == null) return;

    int ok = JOptionPane.showConfirmDialog(
            this,
            "Metode: " + pilih + "\nSimulasi: sudah dibayar?",
            "Konfirmasi Pembayaran",
            JOptionPane.YES_NO_OPTION
    );

    if (ok != JOptionPane.YES_OPTION) return;

    akun.setStatus("Sold Out");
    akun.setBuyerUnlocked(true);

    JOptionPane.showMessageDialog(
            this,
            "Pembayaran sukses ✅\n\nEmail: " + akun.getEmail() +
            "\nPassword: " + akun.getPassword(),
            "Data Akun",
            JOptionPane.INFORMATION_MESSAGE
    );

    akun.setStatus("Sold Out");
    akun.setBuyerUnlocked(true);
    refreshList();

}*/

private java.util.List<AkunGame> getFilteredList() {
    String q = txtSearch.getText().trim().toLowerCase();
    String filter = cbFilter.getSelectedItem().toString();
    String sort = cbSort.getSelectedItem().toString();

    java.util.List<AkunGame> result = new java.util.ArrayList<>();

    // FILTER + SEARCH
    for (AkunGame akun : SystemManager.stok) {

        // filter status
        if (!"Semua".equalsIgnoreCase(filter)) {
            if (!akun.getStatus().equalsIgnoreCase(filter)) continue;
        }

        // search judul
        if (!q.isEmpty()) {
            String judul = akun.getJudul().toLowerCase();
            if (!judul.contains(q)) continue;
        }

        result.add(akun);
    }

    // ===== SORT =====
    if ("Terbaru".equalsIgnoreCase(sort)) {
        // biarin urutan default (yang terakhir ditambah di bawah)
        // supaya terbaru di atas → dibalik
        java.util.Collections.reverse(result);

    } else if ("Terlama".equalsIgnoreCase(sort)) {
        // urutan normal (tidak usah diapa-apain)

    } else if ("Harga".equalsIgnoreCase(sort)) {
        result.sort((a, b) -> Integer.compare(a.getHarga(), b.getHarga()));
    }

    return result;
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuTamu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cbFilter;
    private javax.swing.JComboBox<String> cbSort;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelRoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmail1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
