/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package register_pasien;

/**
 *
 * @author calvi
 */

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPasienGUI
     */
private final java.awt.Color NORMAL = new java.awt.Color(255, 102, 255);
private final java.awt.Color HOVER  = new java.awt.Color(255, 180, 255);


    private void bukaFrame(javax.swing.JFrame frame) {
    frame.setVisible(true);
    this.dispose(); // tutup frame sekarang
    }
    public Home() {

    initComponents();
    // cursor tangan
    lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    
    pnlHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    pnlRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    pnlList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    pnlInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    // semua label bisa diwarnai
    pnlHome.setOpaque(true);
    pnlRegister.setOpaque(true);
    pnlList.setOpaque(true);
    pnlInfo.setOpaque(true);
    
    cardRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cardList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cardInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    cardRegister.setOpaque(true);
    cardList.setOpaque(true);
    cardInfo.setOpaque(true);
    
    java.awt.EventQueue.invokeLater(() -> {
    setSize(950, 835);          // ukuran awal FIX
    setMinimumSize(new java.awt.Dimension(950, 835)); // KUNCI ukuran
    setLocationRelativeTo(null); // tengah layar
    setResizable(false);        // tidak bisa resize
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblWDC = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();
        lblIconHome = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        pnlRegister = new javax.swing.JPanel();
        lblIconRegister = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        pnlList = new javax.swing.JPanel();
        lblIconList = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblIconInfo = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        cardRegister = new javax.swing.JPanel();
        iconRegister = new javax.swing.JLabel();
        txtRegisterTitle = new javax.swing.JLabel();
        txtRegisterDesc = new javax.swing.JLabel();
        cardList = new javax.swing.JPanel();
        iconList = new javax.swing.JLabel();
        txtListTitle = new javax.swing.JLabel();
        txtListDesc = new javax.swing.JLabel();
        cardInfo = new javax.swing.JPanel();
        iconInfo = new javax.swing.JLabel();
        txtInfoTitle = new javax.swing.JLabel();
        txtInfoDesc = new javax.swing.JLabel();
        lblWDC1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblIconWidan = new javax.swing.JLabel();
        lblWDC2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jPanel4.setBackground(new java.awt.Color(255, 102, 255));

        lblWDC.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        lblWDC.setText("Widan Health Care");

        pnlHome.setBackground(new java.awt.Color(255, 102, 255));
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHomeMouseExited(evt);
            }
        });

        lblIconHome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/Home2.png"))); // NOI18N
        lblIconHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseExited(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconHome)
                .addGap(18, 18, 18)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRegister.setBackground(new java.awt.Color(255, 102, 255));
        pnlRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseExited(evt);
            }
        });

        lblIconRegister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIconRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/register50px.png"))); // NOI18N
        lblIconRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconRegisterMouseExited(evt);
            }
        });

        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRegister.setText("Register");

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconRegister)
                .addGap(18, 18, 18)
                .addComponent(lblRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlList.setBackground(new java.awt.Color(255, 102, 255));
        pnlList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlListMouseExited(evt);
            }
        });

        lblIconList.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIconList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/Documentt.png"))); // NOI18N
        lblIconList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconListMouseExited(evt);
            }
        });

        lblList.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblList.setText("List Pasien");

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconList)
                .addGap(18, 18, 18)
                .addComponent(lblList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblList, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInfo.setBackground(new java.awt.Color(255, 102, 255));
        pnlInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlInfoMouseExited(evt);
            }
        });

        lblIconInfo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIconInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/Info1.png"))); // NOI18N
        lblIconInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconInfoMouseExited(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblInfo.setText("Information");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconInfo)
                .addGap(18, 18, 18)
                .addComponent(lblInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lblWDC)
                .addGap(34, 34, 34))
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblWDC)
                .addGap(63, 63, 63)
                .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardRegister.setBackground(new java.awt.Color(255, 255, 255));
        cardRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cardRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardRegisterMouseClicked(evt);
            }
        });

        iconRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/register100px.png"))); // NOI18N

        txtRegisterTitle.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        txtRegisterTitle.setForeground(new java.awt.Color(204, 0, 153));
        txtRegisterTitle.setText("Register Pasien");

        txtRegisterDesc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtRegisterDesc.setText("<html>Digunakan Untuk :<br>Input data nomor, tanggal, nama, umur,alamat, keluhan, terapi.</html>");

        javax.swing.GroupLayout cardRegisterLayout = new javax.swing.GroupLayout(cardRegister);
        cardRegister.setLayout(cardRegisterLayout);
        cardRegisterLayout.setHorizontalGroup(
            cardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardRegisterLayout.createSequentialGroup()
                .addGroup(cardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardRegisterLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(iconRegister))
                    .addGroup(cardRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtRegisterDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtRegisterTitle)))
                .addGap(42, 42, 42))
        );
        cardRegisterLayout.setVerticalGroup(
            cardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegisterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRegisterDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardList.setBackground(new java.awt.Color(255, 255, 255));
        cardList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cardList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardListMouseClicked(evt);
            }
        });

        iconList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/Document2.png"))); // NOI18N

        txtListTitle.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        txtListTitle.setForeground(new java.awt.Color(204, 0, 153));
        txtListTitle.setText("List Pasien");

        txtListDesc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtListDesc.setText("<html>Digunakan Untuk : <br>Melihat, mencari, dan mengedit data pasien yang sudah tersimpan.</html>");

        javax.swing.GroupLayout cardListLayout = new javax.swing.GroupLayout(cardList);
        cardList.setLayout(cardListLayout);
        cardListLayout.setHorizontalGroup(
            cardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardListLayout.createSequentialGroup()
                .addGroup(cardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtListDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardListLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(cardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtListTitle)
                            .addComponent(iconList))))
                .addGap(29, 29, 29))
        );
        cardListLayout.setVerticalGroup(
            cardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(txtListDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardInfo.setBackground(new java.awt.Color(255, 255, 255));
        cardInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cardInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardInfoMouseClicked(evt);
            }
        });

        iconInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/Info100px.png"))); // NOI18N

        txtInfoTitle.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        txtInfoTitle.setForeground(new java.awt.Color(204, 0, 153));
        txtInfoTitle.setText("Information");

        txtInfoDesc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtInfoDesc.setText("<html>Digunakan Untuk :<br>Melihat identitas dan kontak perawat serta jadwal buka harian.</html>");

        javax.swing.GroupLayout cardInfoLayout = new javax.swing.GroupLayout(cardInfo);
        cardInfo.setLayout(cardInfoLayout);
        cardInfoLayout.setHorizontalGroup(
            cardInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardInfoLayout.createSequentialGroup()
                .addGroup(cardInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtInfoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardInfoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(cardInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInfoTitle)
                            .addComponent(iconInfo))))
                .addGap(29, 29, 29))
        );
        cardInfoLayout.setVerticalGroup(
            cardInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInfoTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInfoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblWDC1.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        lblWDC1.setText("Home");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(79, 234));
        jPanel3.setMinimumSize(new java.awt.Dimension(79, 234));
        jPanel3.setPreferredSize(new java.awt.Dimension(79, 234));

        lblIconWidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/logo widan100px.png"))); // NOI18N

        lblWDC2.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        lblWDC2.setForeground(new java.awt.Color(204, 0, 153));
        lblWDC2.setText("Welcome to Widan Health Care");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("<html>✅ Monitoring Kesehatan<br>\n✅ Perawatan Pasien di Rumah<br>\n✅ Edukasi & Konsultasi Keperawatan</html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblIconWidan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWDC2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWDC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblIconWidan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cardRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cardList, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cardInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWDC1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblWDC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cardList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Home());
    }//GEN-LAST:event_lblIconHomeMouseClicked

    private void lblIconHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseEntered
        // TODO add your handling code here:
        pnlHome.setBackground(HOVER);
    }//GEN-LAST:event_lblIconHomeMouseEntered

    private void lblIconHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseExited
        // TODO add your handling code here:
        pnlHome.setBackground(NORMAL);
    }//GEN-LAST:event_lblIconHomeMouseExited

    private void pnlHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Home());
    }//GEN-LAST:event_pnlHomeMouseClicked

    private void pnlHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseEntered
        // TODO add your handling code here:
        pnlHome.setBackground(HOVER);
    }//GEN-LAST:event_pnlHomeMouseEntered

    private void lblIconRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconRegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconRegisterMouseClicked

    private void lblIconRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconRegisterMouseEntered
        // TODO add your handling code here:
        pnlRegister.setBackground(HOVER);
    }//GEN-LAST:event_lblIconRegisterMouseEntered

    private void lblIconRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconRegisterMouseExited
        // TODO add your handling code here:
        pnlRegister.setBackground(NORMAL);
    }//GEN-LAST:event_lblIconRegisterMouseExited

    private void pnlRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Register_Pasien());
    }//GEN-LAST:event_pnlRegisterMouseClicked

    private void pnlRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseEntered
        // TODO add your handling code here:
        pnlRegister.setBackground(HOVER);
    }//GEN-LAST:event_pnlRegisterMouseEntered

    private void lblIconListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconListMouseClicked

    private void lblIconListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseEntered
        // TODO add your handling code here:
        pnlList.setBackground(HOVER);
    }//GEN-LAST:event_lblIconListMouseEntered

    private void lblIconListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseExited
        // TODO add your handling code here:
        pnlList.setBackground(NORMAL);
    }//GEN-LAST:event_lblIconListMouseExited

    private void pnlListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseClicked
        // TODO add your handling code here:
        bukaFrame(new List_Pasien());
    }//GEN-LAST:event_pnlListMouseClicked

    private void pnlListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseEntered
        // TODO add your handling code here:
        pnlList.setBackground(HOVER);
    }//GEN-LAST:event_pnlListMouseEntered

    private void lblIconInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconInfoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconInfoMouseClicked

    private void lblIconInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconInfoMouseEntered
        // TODO add your handling code here:
        pnlInfo.setBackground(HOVER);
    }//GEN-LAST:event_lblIconInfoMouseEntered

    private void lblIconInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconInfoMouseExited
        // TODO add your handling code here:
        pnlInfo.setBackground(NORMAL);
    }//GEN-LAST:event_lblIconInfoMouseExited

    private void pnlInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Information());
    }//GEN-LAST:event_pnlInfoMouseClicked

    private void pnlInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseEntered
        // TODO add your handling code here:
        pnlInfo.setBackground(HOVER);
    }//GEN-LAST:event_pnlInfoMouseEntered

    private void pnlHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseExited
        // TODO add your handling code here:
        pnlHome.setBackground(NORMAL);
    }//GEN-LAST:event_pnlHomeMouseExited

    private void pnlRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseExited
        // TODO add your handling code here:
        pnlRegister.setBackground(NORMAL);
    }//GEN-LAST:event_pnlRegisterMouseExited

    private void pnlListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseExited
        // TODO add your handling code here:
        pnlList.setBackground(NORMAL);
    }//GEN-LAST:event_pnlListMouseExited

    private void pnlInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseExited
        // TODO add your handling code here:
        pnlInfo.setBackground(NORMAL);
    }//GEN-LAST:event_pnlInfoMouseExited

    private void cardRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardRegisterMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Register_Pasien());
    }//GEN-LAST:event_cardRegisterMouseClicked

    private void cardListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardListMouseClicked
        // TODO add your handling code here:
        bukaFrame(new List_Pasien());
    }//GEN-LAST:event_cardListMouseClicked

    private void cardInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardInfoMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Information());
    }//GEN-LAST:event_cardInfoMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Home());
    }//GEN-LAST:event_lblHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardInfo;
    private javax.swing.JPanel cardList;
    private javax.swing.JPanel cardRegister;
    private javax.swing.JLabel iconInfo;
    private javax.swing.JLabel iconList;
    private javax.swing.JLabel iconRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblIconHome;
    private javax.swing.JLabel lblIconInfo;
    private javax.swing.JLabel lblIconList;
    private javax.swing.JLabel lblIconRegister;
    private javax.swing.JLabel lblIconWidan;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblWDC;
    private javax.swing.JLabel lblWDC1;
    private javax.swing.JLabel lblWDC2;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlList;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JLabel txtInfoDesc;
    private javax.swing.JLabel txtInfoTitle;
    private javax.swing.JLabel txtListDesc;
    private javax.swing.JLabel txtListTitle;
    private javax.swing.JLabel txtRegisterDesc;
    private javax.swing.JLabel txtRegisterTitle;
    // End of variables declaration//GEN-END:variables
}
