/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package register_pasien;

/**
 *
 * @author calvi
 */
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;

public class Information extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPasienGUI
     */
private final java.awt.Color NORMAL = new java.awt.Color(255, 102, 255);
private final java.awt.Color HOVER  = new java.awt.Color(255, 180, 255);

    private void bukaFrame(javax.swing.JFrame frame) {
    frame.setVisible(true);
    this.dispose(); // tutup frame sekarang
    }
    public Information() {


    initComponents();
    // cursor tangan
    lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    
    pnlHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    pnlRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    pnlList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    pnlInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    // semua label bisa diwarnai
    pnlHome.setOpaque(true);
    pnlRegister.setOpaque(true);
    pnlList.setOpaque(true);
    pnlInfo.setOpaque(true);
    
    java.awt.EventQueue.invokeLater(() -> {
    setSize(950, 835);          // ukuran awal FIX
    setMinimumSize(new java.awt.Dimension(950, 835)); // KUNCI ukuran
    setLocationRelativeTo(null); // tengah layar
    setResizable(false);        // tidak bisa resize
    });
    
    DefaultTableCellRenderer center = new DefaultTableCellRenderer();
    center.setHorizontalAlignment(JLabel.CENTER);

    // tinggi baris
    jTable1.setRowHeight(28);

    // matikan auto resize
    jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    // atur lebar kolom
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(120); // Hari
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(100); // Jam Buka
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(100); // Jam Tutup

    jTable1.getColumnModel().getColumn(1).setCellRenderer(center);
    jTable1.getColumnModel().getColumn(2).setCellRenderer(center);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblWDC = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();
        lblIconHome = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        pnlRegister = new javax.swing.JPanel();
        lblIconRegister = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        pnlList = new javax.swing.JPanel();
        lblIconList = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblIconInfo = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblWDC1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWDC2 = new javax.swing.JLabel();
        lblWDC3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableJadwalBuka = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableOtherInformation = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(954, 835));
        jPanel2.setMinimumSize(new java.awt.Dimension(954, 835));

        jPanel4.setBackground(new java.awt.Color(255, 102, 255));

        lblWDC.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        lblWDC.setText("Widan Health Care");

        pnlHome.setBackground(new java.awt.Color(255, 102, 255));
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHomeMouseExited(evt);
            }
        });

        lblIconHome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/Home2.png"))); // NOI18N
        lblIconHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconHomeMouseExited(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHome.setText("Home");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconHome)
                .addGap(18, 18, 18)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRegister.setBackground(new java.awt.Color(255, 102, 255));
        pnlRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRegisterMouseExited(evt);
            }
        });

        lblIconRegister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIconRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/register50px.png"))); // NOI18N
        lblIconRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconRegisterMouseExited(evt);
            }
        });

        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRegister.setText("Register");

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconRegister)
                .addGap(18, 18, 18)
                .addComponent(lblRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlList.setBackground(new java.awt.Color(255, 102, 255));
        pnlList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlListMouseExited(evt);
            }
        });

        lblIconList.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIconList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/Documentt.png"))); // NOI18N
        lblIconList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconListMouseExited(evt);
            }
        });

        lblList.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblList.setText("List Pasien");

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconList)
                .addGap(18, 18, 18)
                .addComponent(lblList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblList, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInfo.setBackground(new java.awt.Color(255, 102, 255));
        pnlInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlInfoMouseExited(evt);
            }
        });

        lblIconInfo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblIconInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/Info1.png"))); // NOI18N
        lblIconInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconInfoMouseExited(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblInfo.setText("Information");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconInfo)
                .addGap(18, 18, 18)
                .addComponent(lblInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIconInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lblWDC)
                .addGap(34, 34, 34))
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblWDC)
                .addGap(63, 63, 63)
                .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        lblWDC1.setFont(new java.awt.Font("Vladimir Script", 1, 36)); // NOI18N
        lblWDC1.setText("Information");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.setMaximumSize(new java.awt.Dimension(539, 666));
        jPanel1.setMinimumSize(new java.awt.Dimension(539, 666));
        jPanel1.setPreferredSize(new java.awt.Dimension(543, 666));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_pasien/logo widan220px.png"))); // NOI18N

        lblWDC2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblWDC2.setForeground(new java.awt.Color(204, 0, 153));
        lblWDC2.setText("<html>Perawat 1 :  Candra Pratiwi, S.kep. Ns<br>\nNo. WA    : 085111111111</html>");

        lblWDC3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblWDC3.setForeground(new java.awt.Color(204, 0, 153));
        lblWDC3.setText("<html>Perawat 2 : Danang Priyo Utomo, A.md, Kep.<br>\nNo. WA    : 085222222222</html>");

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(41, 36));

        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setMaximumSize(null);
        jScrollPane2.setMinimumSize(null);

        TableJadwalBuka.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TableJadwalBuka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Senin", "15:00", "21:00"},
                {"Selasa", "15:00", "21:00"},
                {"Rabu", "15:00", "21:00"},
                {"Kamis", "15:00", "21:00"},
                {"Jumat", "15:00", "21:00"},
                {"Sabtu", "15:00", "21:00"},
                {"Minggu", "08:00", "21:00"}
            },
            new String [] {
                "Hari", "Jam Buka", "Jam Tutup"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableJadwalBuka.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TableJadwalBuka.setEnabled(false);
        TableJadwalBuka.setRowHeight(28);
        jScrollPane2.setViewportView(TableJadwalBuka);

        jTabbedPane1.addTab("tab1", jScrollPane2);

        TableOtherInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Menyesuaikan Hari libur Perawat juga"}
            },
            new String [] {
                "Info 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableOtherInformation.setAlignmentX(1.0F);
        TableOtherInformation.setAlignmentY(1.0F);
        jScrollPane3.setViewportView(TableOtherInformation);

        jTabbedPane1.addTab("tab2", jScrollPane3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWDC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWDC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWDC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWDC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWDC1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblWDC1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconHomeMouseClicked

    private void lblIconHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseEntered
        // TODO add your handling code here:
        pnlHome.setBackground(HOVER);
    }//GEN-LAST:event_lblIconHomeMouseEntered

    private void lblIconHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHomeMouseExited
        // TODO add your handling code here:
        pnlHome.setBackground(NORMAL);
    }//GEN-LAST:event_lblIconHomeMouseExited

    private void pnlHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Home());
    }//GEN-LAST:event_pnlHomeMouseClicked

    private void pnlHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseEntered
        // TODO add your handling code here:
        pnlHome.setBackground(HOVER);
    }//GEN-LAST:event_pnlHomeMouseEntered

    private void lblIconRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconRegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconRegisterMouseClicked

    private void lblIconRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconRegisterMouseEntered
        // TODO add your handling code here:
        pnlRegister.setBackground(HOVER);
    }//GEN-LAST:event_lblIconRegisterMouseEntered

    private void lblIconRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconRegisterMouseExited
        // TODO add your handling code here:
        pnlRegister.setBackground(NORMAL);
    }//GEN-LAST:event_lblIconRegisterMouseExited

    private void pnlRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Register_Pasien());
    }//GEN-LAST:event_pnlRegisterMouseClicked

    private void pnlRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseEntered
        // TODO add your handling code here:
        pnlRegister.setBackground(HOVER);
    }//GEN-LAST:event_pnlRegisterMouseEntered

    private void lblIconListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconListMouseClicked

    private void lblIconListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseEntered
        // TODO add your handling code here:
        pnlList.setBackground(HOVER);
    }//GEN-LAST:event_lblIconListMouseEntered

    private void lblIconListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconListMouseExited
        // TODO add your handling code here:
        pnlList.setBackground(NORMAL);
    }//GEN-LAST:event_lblIconListMouseExited

    private void pnlListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseClicked
        // TODO add your handling code here:
        bukaFrame(new List_Pasien());
    }//GEN-LAST:event_pnlListMouseClicked

    private void pnlListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseEntered
        // TODO add your handling code here:
        pnlList.setBackground(HOVER);
    }//GEN-LAST:event_pnlListMouseEntered

    private void lblIconInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconInfoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconInfoMouseClicked

    private void lblIconInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconInfoMouseEntered
        // TODO add your handling code here:
        pnlInfo.setBackground(HOVER);
    }//GEN-LAST:event_lblIconInfoMouseEntered

    private void lblIconInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconInfoMouseExited
        // TODO add your handling code here:
        pnlInfo.setBackground(NORMAL);
    }//GEN-LAST:event_lblIconInfoMouseExited

    private void pnlInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseClicked
        // TODO add your handling code here:
        bukaFrame(new Information());
    }//GEN-LAST:event_pnlInfoMouseClicked

    private void pnlInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseEntered
        // TODO add your handling code here:
        pnlInfo.setBackground(HOVER);
    }//GEN-LAST:event_pnlInfoMouseEntered

    private void pnlHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseExited
        // TODO add your handling code here:
        pnlHome.setBackground(NORMAL);
    }//GEN-LAST:event_pnlHomeMouseExited

    private void pnlRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegisterMouseExited
        // TODO add your handling code here:
        pnlRegister.setBackground(NORMAL);
    }//GEN-LAST:event_pnlRegisterMouseExited

    private void pnlListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListMouseExited
        // TODO add your handling code here:
        pnlList.setBackground(NORMAL);
    }//GEN-LAST:event_pnlListMouseExited

    private void pnlInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoMouseExited
        // TODO add your handling code here:
        pnlInfo.setBackground(NORMAL);
    }//GEN-LAST:event_pnlInfoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableJadwalBuka;
    private javax.swing.JTable TableOtherInformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblIconHome;
    private javax.swing.JLabel lblIconInfo;
    private javax.swing.JLabel lblIconList;
    private javax.swing.JLabel lblIconRegister;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblWDC;
    private javax.swing.JLabel lblWDC1;
    private javax.swing.JLabel lblWDC2;
    private javax.swing.JLabel lblWDC3;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlList;
    private javax.swing.JPanel pnlRegister;
    // End of variables declaration//GEN-END:variables
}
